# Local image for spec linting and SRPM builds:
#   podman build -t localhost/rpmlint:local -f tools/Containerfile.rpmlint tools/
FROM registry.fedoraproject.org/fedora:44
RUN dnf -y install rpmlint rpm-build rpmdevtools git-core && dnf clean all
WORKDIR /src
USER 1000
